# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ea48297e905257bd0de974340df97b50812d6f50a8c85b93906c6015ba6b4cf6717277894acb4d43a2ec079ada7702e038a872ba4bb03eee1b546edc46dd0bd

test:
  secret_key_base: b0fa603b2dbf4e935c07a8ffb1589b74c5037811a529846bb1432d1e391c8ec535ccc19ec0760c69e14ea4218d25f9b95ea3e69881b8e444b6b2a4d9f7c96711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
